name: C/C++ CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: mkdir build
              run: mkdir -p build
            - name: build
              run: cd build &&
                  cmake
                    -DCMAKE_CXX_COMPILER=g++-9
                  .. &&
                  make -j$(nproc)
