name: C/C++ CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: mkdir build
              run: mkdir -p build
            - name: configure
              run: cd build && cmake ..
            - name: make 
              run: make 
